// app/tutors/strings.ts —— /tutors 與 /tutors/[slug] 兩頁自己的 UI 字串。
// 值為 {zh, en}，交給 lib/i18n 的 t() 取字。mock 內容（自傳、評價、方案內文）不在這裡，維持中文原文。
// 領域字串為原字串常數（首頁分類導覽與 ?domain= 都用這幾個）。

export const DOMAINS = ['LLM 應用', 'Agent 開發', '電腦視覺', 'MLOps', '資料科學', 'AI 入門'] as const;
export type Domain = (typeof DOMAINS)[number];

// 領域顯示標籤（中文原字串當 key，英文另給）
export const domainLabel: Record<Domain, { zh: string; en: string }> = {
  'LLM 應用': { zh: 'LLM 應用', en: 'LLM Apps' },
  'Agent 開發': { zh: 'Agent 開發', en: 'Agent Dev' },
  '電腦視覺': { zh: '電腦視覺', en: 'Computer Vision' },
  MLOps: { zh: 'MLOps', en: 'MLOps' },
  '資料科學': { zh: '資料科學', en: 'Data Science' },
  'AI 入門': { zh: 'AI 入門', en: 'AI Basics' },
};

export const s = {
  // ---- 列表頁 ----
  listKicker: { zh: '講師目錄', en: 'Tutor directory' },
  listTitle: { zh: '找講師', en: 'Find a tutor' },
  listSubtitle: {
    zh: '用領域、程度、預算篩出最適合你的 AI 講師。每張側寫都由引擎讀過 GitHub 與作品後生成。',
    en: 'Filter AI tutors by domain, level and budget. Every profile is drawn from the engine reading their GitHub and work.',
  },
  filterHeading: { zh: '篩選', en: 'Filter' },
  filterDomain: { zh: '領域', en: 'Domain' },
  filterLevel: { zh: '程度', en: 'Level' },
  filterRate: { zh: '時薪', en: 'Hourly rate' },
  filterProjects: { zh: '只看可接案', en: 'Open to projects only' },
  rateAny: { zh: '不限', en: 'Any' },
  rateLow: { zh: 'NT$1000 以下', en: 'Under NT$1000' },
  rateMid: { zh: 'NT$1000–1800', en: 'NT$1000–1800' },
  rateHigh: { zh: 'NT$1800 以上', en: 'Over NT$1800' },
  resultCount: { zh: '位講師', en: 'tutors' },
  empty: {
    zh: '沒有符合條件的講師，試著放寬篩選。',
    en: 'No tutors match. Try loosening the filters.',
  },
  clearFilters: { zh: '清除篩選', en: 'Clear filters' },

  // ---- 個人頁 ----
  perHour: { zh: ' /時', en: ' /hr' },
  book: { zh: '預約試教', en: 'Book a trial' },
  bookToast: {
    zh: 'Demo 版尚未開放預約，歡迎以訪客身份繼續探索',
    en: 'Booking is not open in this demo. Feel free to keep exploring as a guest.',
  },
  aiProfileTitle: { zh: 'AI 能力側寫', en: 'AI skill profile' },
  aiProfileTag: { zh: '由 AvoMole AI 引擎生成', en: 'Generated by the AvoMole AI engine' },
  profileKicker: { zh: '能力側寫', en: 'Capability profile' },
  radarLabel: { zh: '六軸能力', en: 'Six-axis skills' },
  summaryLabel: { zh: '引擎摘要', en: 'Engine summary' },
  difficulty: { zh: '專案難度', en: 'Project difficulty' },
  teachLevels: { zh: '適教程度', en: 'Teaches' },
  githubTitle: { zh: 'GitHub', en: 'GitHub' },
  stars: { zh: '星', en: 'stars' },
  langDist: { zh: '語言分佈', en: 'Language mix' },
  portfolioTitle: { zh: '作品集', en: 'Portfolio' },
  viewProject: { zh: '看專案', en: 'View project' },
  reviewsTitle: { zh: '學生評價', en: 'Reviews' },
  reviewDigest: { zh: 'AI 評價摘要', en: 'AI review summary' },
  plansTitle: { zh: '課程方案', en: 'Plans' },
  endorsementsTitle: { zh: '名人推薦', en: 'Endorsements' },
  demoContentZh: { zh: '', en: 'Demo content in Chinese' },
  backToList: { zh: '← 回講師列表', en: '← Back to tutors' },
} as const;
